name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: DoSomething
      run: |
        docker pull cgr.dev/chainguard/apko
